spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
#    url: jdbc:h2:mem:querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #app ??? entity table ??
    properties:
      hibernate:
#        show_sql: true #sysout hibernate execute query
        format_sql: true #query formatting

logging.level:
  org.hibernate.SQL: debug #logger hibernate execute query
  org.hibernate.type: trace #print binding parameter

